title = "Dev Damien"
baseURL = "dev.Damien"
languageCode = "en-gb"

# This is just to get the exampleSite to work with the theme 
# in this repository. Don't mimic this. When using the theme
# you should place it in themes/codex and list theme = "codex"
theme = "hugo-theme-codex"




[params]
  # This will show the twitter icon which will link to twitter.com/your-twitter-handle
  # You can omit the @ symbol
  twitter = "damiensaunders"
  # This will show the github icon which will link to github.com/your-github-handle
  # You can omit the @ symbol
  github = "damien1"
