# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBasic():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_basic(self):
    self.driver.get("http://localhost:9081/")
    self.driver.set_window_size(1000, 800)
    assert self.driver.title == "Airspace | Creative Agency Hugo Template"
    self.driver.set_window_size(400, 600)
    self.driver.find_element(By.CSS_SELECTOR, ".navbar-toggle").click()
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'About\')]").click()
    assert self.driver.title == "About Our Company"
    self.driver.set_window_size(1000, 800)
    self.driver.find_element(By.XPATH, "//a[contains(text(),\'Blog\')]").click()
    self.driver.find_element(By.XPATH, "(//a[@href=\'http://localhost:9081/blog/font/\'])[2]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".post-content > div:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".post-content > div:nth-child(5)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".post-content > div:nth-child(5)")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".post-content > div:nth-child(5)")
    assert len(elements) > 0
  
